version: '3.8'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: 'email-api-nestjs'
    image: 'email-api-nestjs:20.11.1'
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
volumes:
  pgdata:
