version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - APP_PORT:${APP_PORT}
      - JWT_SECRET:${JWT_SECRET}
      - DATABASE_URL:${DATABASE_URL}
    depends_on:
      - db
    ports:
      - 7000:7000
    restart: always
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always