
services:
  api:
    container_name: email-api
    image: email-api:lts
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: email-db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"